#!/bin/bash -e
#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Downloads and extracts heliotrope jar
#  Usage: bin/download-heliotrope <version> # get version from https://artifacts.oicr.on.ca/artifactory/dcc-dependencies/org/icgc/dcc/dcc-heliotrope (highest directory number)

if [ "$(basename $PWD)" != "dcc-import" ]; then
 echo "Must be in dcc-import directory"
 exit 1
fi
if [ -z "$1" ] 
  then echo "No version supplied"; exit 1;
fi

wget https://artifacts.oicr.on.ca/artifactory/dcc-dependencies/org/icgc/dcc/dcc-heliotrope/$1/dcc-heliotrope-$1.jar;
jar xf dcc-heliotrope-$1.jar data/genes.bson;
rm dcc-heliotrope-$1.jar;
