#!/bin/bash -e
#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#
# Downloads Projects.json 
#  Usage: bin/download-projects
#

if [ "$(basename $PWD)" != "dcc-import" ]; then
 echo "Must be in dcc-import directory"
 exit 1
fi

github_username=<username>
data_dir="***REMOVED***/dcc-import/data"

passwd_file="***REMOVED***"
github_passwd=$(cat ${passwd_file?} | awk -F'=' '/github\.'${github_username?}'/{print $2}')
mv ${data_dir?}/Project.json ${data_dir?}/Project.json.bak || :
curl -u ${github_username?}:${github_passwd?} -L -o ${data_dir?}/Projects.json https://raw.github.com/icgc-dcc/dcc/develop/dcc-etl/dcc-etl-client/src/test/resources/dcc-project/Project.json?login=$1&token=<token_id>
