#!/bin/bash -e
#
# Downloads Projects.json 
#  Usage: bin/download-projects
#

if [ "$(basename $PWD)" != "dcc-import" ]; then
 echo "Must be in dcc-import directory"
 exit 1
fi

github_username=***REMOVED***
data_dir="***REMOVED***/dcc-import/data"

passwd_file="***REMOVED***"
github_passwd=$(cat ${passwd_file?} | awk -F'=' '/github\.'${github_username?}'/{print $2}')
mv ${data_dir?}/Project.json ${data_dir?}/Project.json.bak || :
curl -u ${github_username?}:${github_passwd?} -L -o ${data_dir?}/Projects.json https://raw.github.com/icgc-dcc/dcc/develop/dcc-etl/dcc-etl-client/src/test/resources/dcc-project/Project.json?login=$1&token=***REMOVED***
