#!/bin/bash
# usage: bin/import-genes my_mongodb_server

mongodb_server=${1?} && shift
dcc_username=${1?} && shift
dcc_passwd=${1?} && shift

if [ "$(basename $PWD)" != "dcc-import" ]; then
 echo "Must be in dcc-import directory"
 exit 1
fi
java -jar lib/dcc-genes-1.6-SNAPSHOT.jar -d mongodb://${dcc_username?}:${dcc_passwd?}@${mongodb_server?}/dcc-genome.Gene -f data/genes.bson
