#!/bin/bash -e
# Downloads and extracts heliotrope jar
#  Usage: bin/download-heliotrope <version> # get version from http://seqwaremaven.oicr.on.ca/artifactory/dcc-dependencies/org/icgc/dcc/dcc-heliotrope (highest directory number)

if [ "$(basename $PWD)" != "dcc-import" ]; then
 echo "Must be in dcc-import directory"
 exit 1
fi
if [ -z "$1" ] 
  then echo "No version supplied"; exit 1;
fi

wget http://seqwaremaven.oicr.on.ca/artifactory/dcc-dependencies/org/icgc/dcc/dcc-heliotrope/$1/dcc-heliotrope-$1.jar;
jar xf dcc-heliotrope-$1.jar data/genes.bson;
rm dcc-heliotrope-$1.jar;
