\set DEFAULT_RELEASE '\'ICGC14\''

ALTER TABLE donor_ids ADD COLUMN creation_release VARCHAR(512) NOT NULL DEFAULT :DEFAULT_RELEASE;
ALTER TABLE donor_ids ALTER COLUMN creation_release DROP DEFAULT;

ALTER TABLE project_ids ADD COLUMN creation_release VARCHAR(512) NOT NULL DEFAULT :DEFAULT_RELEASE;
ALTER TABLE project_ids ALTER COLUMN creation_release DROP DEFAULT;

ALTER TABLE specimen_ids ADD COLUMN creation_release VARCHAR(512) NOT NULL DEFAULT :DEFAULT_RELEASE;
ALTER TABLE specimen_ids ALTER COLUMN creation_release DROP DEFAULT;

ALTER TABLE sample_ids ADD COLUMN creation_release VARCHAR(512) NOT NULL DEFAULT :DEFAULT_RELEASE;
ALTER TABLE sample_ids ALTER COLUMN creation_release DROP DEFAULT;

ALTER TABLE mutation_ids ADD COLUMN creation_release VARCHAR(512) NOT NULL DEFAULT :DEFAULT_RELEASE;
ALTER TABLE mutation_ids ALTER COLUMN creation_release DROP DEFAULT;
