#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# FileSystem Scheme. This sets hadoop's fs.defaultFS
fsUrl: "file:///"

# URI to the submission system web app
submissionWebAppUri: localhost

# Whether to filter out CONTROLLED field for all outputs of the loader or simply for mongodb
filterAllControlled: false

# Specify compression type for the output of the loader to be consumed by the exporter
fileSystemOutputCompression: NONE

# Specifies the number of maximum concurrent flows in the loader phase 
loaderMaxConcurrentFlows: 100

# ElasticSearch URI
esUri: "es://localhost:9300"

# Submission MongoDB URI
submissionMongoUri: "mongodb://localhost/icgc-local"

# Release MongoDB URI (do not specify a database)
releaseMongoUri: "mongodb://localhost"

# Admin URI (necessary for mongoinit component to satisfy mongo splitVector's permissions in the ETL)
etlAdminMongoUri: "mongodb://localhost"

# DCC Identifier Service
identifierServiceUri: "http://<host>:<port>"

# Project MongoDB URI
projectMongoUri: "mongodb://localhost/dcc-project"

# Gene MongoDB URI
geneMongoUri: "mongodb://localhost/dcc-import"

# CGHub BSON dump
cghubFile: "target/cghub.bson"

# rsmd.sh project donor summaries output directoy
# summaryDir: "target/reports"

# FASTA file for VCF generation
fastaFile: "/tmp/GRCh37.fasta"

# Fathmm Postgresql
fathmmPostgresqlUri: "jdbc:postgresql://localhost:5432/fathmm"

# Export mutation VCF file
exportVCF: true

# Hadoop configuration
loaderHadoop:
  fs.defaultFS: "file:///"
  mapred.job.tracker : "localhost:8021"
  #mapred.job.shuffle.input.buffer.percent: 0.5
  #mongo.input.split.create_input_splits: "false"
  #mongo.input.split_size: 256
  #mapred.child.java.opts: "-Xmx1g"
  #io.sort.mb: 500
  #mapred.reduce.tasks=1
indexerHadoop:
  fs.defaultFS: "file:///"
  #mapred.map.child.java.opts: "-Xmx31g -XX:MaxDirectMemorySize=31g"
 
# ICGC Client configuration
icgc:
  cgpServiceUrl: ""
  cudServiceUrl: ""
  shortServiceUrl: ""
  consumerKey: ""
  consumerSecret: ""
  accessToken: ""
  accessSecret: ""
  cudAppId: ""
  strictSSLCertificates: true
  requestLoggingEnabled: false
